### ISSUE TITLE
Stable?

### ISSUE THREAD

**Issue by tommedema** [jonschlinkert/array-sort#15]
Surprisingly it's not mentioned anywhere if this is a stable / deterministic sort. And also which algorithm is used, like timsort?

**Comment by doowb** [comment]
Hi @tommedema this is something that I had considered when creating [default-compare](https://github.com/doowb/default-compare) which is the ... default comparison function passed to `arr.sort` in this library. Since the algorithm will return 0 when values are the same then the sorting cannot be deterministic because internally JavaScript may put one value in front of another.

However, in [custom comparison functions](https://github.com/jonschlinkert/array-sort/blob/master/examples/custom-functions.js) may be passed in, you can choose to sort differently (the regular compare function is passed in so you can do something like below if your objects look like this):

```js
const sort = require('array-sort');
const arr = [{id: 567, name: 'doowb'}, {id: 345, name: 'tommedema'}, {id: 123, name: 'doowb'}, {id: 987, name: 'jonschlinkert'}];

const sorted = sort(arr, function(a, b, compare) {
  const res = compare(a.name, b.name);
  if (res === 0) {
    if (a.id > b.id) return 1;
    if (a.id < b.id) return -1;
  }
  return res;
});

console.log(sorted);
// => [ { id: 123, name: 'doowb' },
// =>   { id: 567, name: 'doowb' },
// =>   { id: 987, name: 'jonschlinkert' },
// =>   { id: 345, name: 'tommedema' } ]
```

I hope this helps answer your question. I'm going to close this, but if you have an issue using the library in the way described, please feel free to open an issue about that.
