### ISSUE TITLE
No compatible call signatures

### ISSUE THREAD

**Issue by JacobCoder1** [jonschlinkert/array-sort#16]
Using array-sort in typescript for around 16 months, but am now faced wit:

Cannot invoke an expression whose type lacks a call signature. Type '{}' has no compatible call signatures.ts(2349)

Everytime I try use it, even when using the readme files. Has TS update caused this?

**Comment by doowb** [comment]
> Has TS update caused this?

Sounds like it's a TS issue since nothing has changed in this package. Also, there aren't any type definitions published in this package, so if you have some from someplace else you might want to check to see if those have changed for any reason.

I'm going to close this, but if you think there's an issue with `array-sort`, please feel free to add additional information (code, environment information, etc...) so someone can help.
